name: NFL Data Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Set up Firebase auth
      - name: Setup Firebase service account
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_KEY }}" > firebase_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase_key.json

      # 5️⃣ Run data ingestion
      - name: Run data ingestion
        run: python scripts/data_ingestion.py

      # 6️⃣ Run data cleaning
      - name: Run data cleaning
        run: python scripts/data_cleaning.py

      # 7️⃣ Run feature engineering
      - name: Run feature engineering
        run: python scripts/player_prop_features.py
